apiVersion: v1
kind: Service
metadata:
  name: {{ include "fake-stackoverflow.fullname" . }}
  labels:
    {{- include "fake-stackoverflow.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "fake-stackoverflow.fullname" . }}
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fake-stackoverflow.selectorLabels" . | nindent 4 }}

### expose swagger to the internet, or setup port-forward explnation 
